name: Dev Prod Actions 5


on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
  

jobs:
  train_on_dev:
    if: github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install azureml-core
        run: pip install azureml-core
      - name: Install Flake8
        run: |
          python -m pip install flake8
      - name: Run linting tests
        run: | 
          flake8 src/model/
      - name: Run pytest tests
        run: pytest tests/test_train.py
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
      - name: Trigger dev model training
        run: >-
          az ml job create
          --file src/job_dev_prod.yml
          --resource-group rg-dp100-labs
          --workspace-name mlw-dp100-labs
          
  train_on_prod:
    if: github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install azureml-core
        run: pip install azureml-core
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
      - name: Trigger dev model training
        run: >-
          az ml job create
          --file src/job_dev_prod.yml
          --set inputs.my_data_input.path=${{ env.DATA_PATH }}
          --set inputs.dev_prod=${{ env.DEV_PROD }}
          --resource-group rg-dp100-labs
          --workspace-name mlw-dp100-labs
        env:
          #DATA_PATH: 'azureml:https://dbricksstorageigor.blob.core.windows.net/microsoft-mlops-training/production/data'
          DATA_PATH: 'azureml://datastores/microsoft_mlops_training/paths/production/data'
          DEV_PROD: '1'