name: Run Tests on Push 5


on:
  push:
    branches:
      - feature1
      - feature1/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install Flake8
        run: |
          python -m pip install flake8
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
      - name: Run linting tests
        run: | 
          flake8 src/model/
      - name: Run pytest tests
        run: pytest tests/test_train.py
