name: Run Tests on Push 3


on:
  push:
    branches:
      - feature1
      - feature1/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
      #- name: Run tests
        #run: pytest
